language: python

services:
  - docker
  - mysql

branches:
  only:
  - master

install:
  - pip install -r requirements.txt

before_script:
  - mysql -u root --password="" < TestCases/travis.sql

script:
  - python -m unittest discover TestCases
  - make travis
